### ISSUE TITLE
Authorization HTTP header is inserted as parameter even though there is securityScheme defined

### ISSUE THREAD

**Issue by ipepe** [exoego/rspec-openapi#160]
I have defined securitySchemes as follows:
```yaml
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: AUTHORIZATION
```

But when I'm generating a schema file, seems like `AUTHORIZATION` header is being constantly suggested as parameter:

```yaml
      parameters:
      - name: AUTHORIZATION
        in: header
        required: true
        schema:
          type: string
        example: AuthorizationExampleSecretKey
```

From my understanding this isn't necessary or even contradicts to OpenAPI specification. Can we somehow parse `securitySchemes` for headers that should not be added as parameters?
