### ISSUE TITLE
Manually edited oneOf in response schema is overridden

### ISSUE THREAD

**Issue by simba909** [exoego/rspec-openapi#173]
I'm evaluating this gem for a project I'm working on and it looks _much_ nicer than rswag. Well done! 👏🏻 

Sorry for the long message that follows.

Now, my Rails app has a model that itself has a property that can be an instance of several different sub-models. The JSON for this can look something like:
```json
{
  "name": "some_name",
  "data": {
    "email": "someone@example.com"
  }
}
```

or:
```json
{
  "name": "some_name",
  "data": {
    "selfie_url": "https://somewhere.com/public/image.jpg"
  }
}
```

I have request specs that return both variants of this model. By default rspec-openapi generates an OpenAPI spec that looks something like this:
```yaml
components:
  schemas:
    MyModel:
      type: object
      properties:
        name:
          type: string
        data:
          type: object
          properties:
            email:
              nullable: true
            selfie_url:
              nullable: true
```

Which is fine but not quite what I want. I'd like to use the `oneOf` keyword to differentiate the response types. So I edit my OpenAPI spec to look like this:
```yaml
components:
  schemas:
    MyModel:
      type: object
      properties:
        name:
          type: string
        data:
          oneOf:
            - type: object
              properties:
                email:
                  type: string
                  format: email
            - type: object
               properties:
                 selfie_url:
                   type: string
                   format: uri
```

But when I rerun the spec generation, rspec-openapi alters the spec to this:
```yaml
components:
  schemas:
    MyModel:
      type: object
      properties:
        name:
          type: string
        data:
          oneOf:
            - type: object
              properties:
                email:
                  type: string
                  format: email
            - type: object
               properties:
                 selfie_url:
                   type: string
                   format: uri
            type: object
            properties:
              email:
                nullable: true
              selfie_url:
                nullable: true
```

Notice that it keeps my `oneOf:` but adds back the sub-model with all properties being `nullable`. Is this a known limitation or something I'm doing wrong?

**Comment by hss-mateus** [comment]
Same issue here. Reading through the source code it seems that this case isn't handled.
A possible implementation is to find the most similar schema, merge it, and if no schema is sufficiently similar, a new option is added to `oneOf`.

**Comment by exoego** [comment]
```yaml
        data:
          oneOf:
            - type: object
              properties:
                email:
                  type: string
                  format: email
            - type: object
               properties:
                 selfie_url:
                   type: string
                   format: uri
            type: object
            properties:
              email:
                nullable: true
              selfie_url:
                nullable: true
```

It looks weird. `oneOf` mixes array elements `- ...` and object properties `type: ...`.
Was that YAML/JSON generated?
