### ISSUE TITLE
Implicit dependence on rails on 0.12.0

### ISSUE THREAD

**Issue by AlexeyMatskevich** [exoego/rspec-openapi#176]
After updating the dependencies, I noticed that the `parsed_body`https://github.com/exoego/rspec-openapi/blob/5469c81f4671d70d14963813ad5c67cca03ce47e/lib/rspec/openapi/record_builder.rb#L43-L47 uses new code from `action_dispatch/testing/request_encoder.rb`.
https://github.com/rails/rails/blob/main/actionpack/lib/action_dispatch/testing/request_encoder.rb#L57
```ruby
register_encoder :html, response_parser: -> body { Rails::Dom::Testing.html_document.parse(body) }
```

Since rspec-openapi depends on actionpack this leads to dependency on rails regardless of the rails-dom-testing installation.

My project uses Roda and Hanami and no rails.

```
Failures:

  1) #create-account NOT create new account
     Failure/Error: example.run

     NameError:
       uninitialized constant ActionDispatch::RequestEncoder::Rails
     # /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_dispatch/testing/request_encoder.rb:55:in `block in <class:RequestEncoder>'
     # /usr/local/bundle/gems/actionpack-7.1.3.2/lib/action_dispatch/testing/test_response.rb:50:in `parsed_body'
     # /usr/local/bundle/bundler/gems/rspec-openapi-5469c81f4671/lib/rspec/openapi/record_builder.rb:44:in `safe_parse_body'
     # /usr/local/bundle/bundler/gems/rspec-openapi-5469c81f4671/lib/rspec/openapi/record_builder.rb:34:in `build'
     # /usr/local/bundle/bundler/gems/rspec-openapi-5469c81f4671/lib/rspec/openapi/rspec_hooks.rb:8:in `block in <top (required)>'
     # ./spec/support/database_cleaner.rb:23:in `block (4 levels) in <top (required)>'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
     # ./spec/support/database_cleaner.rb:22:in `block (3 levels) in <top (required)>'
     # /usr/local/bundle/gems/database_cleaner-core-2.0.1/lib/database_cleaner/strategy.rb:30:in `cleaning'
     # ./spec/support/database_cleaner.rb:21:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/webmock-3.23.0/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```
