### ISSUE TITLE
Is there a way to name `[]` in parameters?

### ISSUE THREAD

**Issue by lion-man44** [exoego/rspec-openapi#234]
This is a question.
Is there "proper" way to output this format?

```yaml
      parameters:
      - name: 'user_ids[]' << this one
        in: query
        required: false
        schema:
          type: array
          items:
            type: string
```

Our front generate `type.d.ts` using this openapi file, and rails way is allowed by this `user_ids[]=1&user_ids[]=2`
