### ISSUE TITLE
Invalid specs because of missing type + nullable: true

### ISSUE THREAD

**Issue by dgmora** [exoego/rspec-openapi#237]
In some cases, when there's a request that returns an empty attribute, the following is generated:

```
                    myattribute:
                            nullable: true
```
Without any type (because it can't be inferred). This is not valid. While not perfect, would it be possible to generate something like this, if there is no type that can be used?

```
                  myattribute:
                    nullable: true
                    oneOf:
                      - type: string
                      - type: number
                      - type: boolean
                      - type: object
                      - type: array
```

This is at least a valid definition.
